services:
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    ports:
      - '3309:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gamelle_api_database
    command: --default-authentication-plugin=mysql_native_password + 'bash -c "npx prisma migrate dev"'
  server:
    build: ./server
    ports:
      - 4000:4000
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/gamelle_api_database
    command: 'bash -c "yarn && yarn global add typescript && yarn start && npx prisma migrate dev"'
    volumes: 
      - ./server/src/:/server/src/
  # client:
  #   build: ./client
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./client/src/:/client/src/
