services:
  mysql:
    container_name: mysql-docker
    restart: always
    image: 'mysql:8.0.22'
    ports:
      - '3309:3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mont_blanc_ticket
    volumes:
      - ./db-volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
        test: "mysql -u root -proot --execute 'SHOW DATABASES;'"
        interval: 5s
        retries: 20
  server:
    build: ./server
    restart: always
    ports:
      - 4000:4000
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - REQUEST_ORIGIN=http://localhost:5000/
      - DATABASE_URL=mysql://root:root@host.docker.internal:3309/mont_blanc_ticket
    command: 'npx prisma migrate dev && yarn start'
    volumes: 
      - ./server/src/:/server/src/
    healthcheck:
        test: ["CMD", "curl", "127.0.0.1:4000/graphql"]
        interval: 5s
        retries: 20
  client:
    build: ./client
    restart: always
    ports:
      - 3000:3000
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./client/src/:/client/src/
    command: 'yarn start'
