name: deploy-client-staging

on:
  push:
    branches:
      - "staging"

jobs:
  build-client-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: cd client && docker build -t cyrheel/wns-client .
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Send to DockerHUB
        run: docker push cyrheel/wns-client

  build-server-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: cd server && docker build -t cyrheel/wns-server .
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Send to DockerHUB
        run: docker push cyrheel/wns-server
